disabled_rules:
  # - todo

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  # - conditional_returns_on_newline # kwatson: I prefer this, but this seems a common pattern in the project
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - discouraged_optional_collection # kwatson: maybe?
  - empty_count
  - empty_string
  - explicit_init
  # - explicit_type_interface # kwatson: may improve build times, but type inference is nice
  - fallthrough
  - first_where
  - function_default_parameter_at_end # kwatson: personal preference... can remove
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - no_grouping_extension # kwatson: maybe?
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

